server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /unionManagementApi
    encoding:
      charset: utf-8
spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/union_management?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
    druid:
      # 初始化,最小,最大连接数
      initial-size: 5
      #获取数据库连接等待的超时时间
      min-idle: 5
      max-active: 20
      max-wait: 60000
      #配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      pool-prepared-statements: true
      #配置监控统计拦截的filters，去掉后,监控界面的sql无法统计
      filters: stat,wall
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: true
        url-pattern: /druid/*
        allow:
        #deny优先级高于allow
        deny:
      web-stat-filter:
        enabled: true
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        url-pattern: /*
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    multipart:
      max-file-size: 4096MB
      max-request-size: 4096MB


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: state  # 全局逻辑删除的实体字段名
      logic-delete-value: X # 逻辑已删除值(默认为 1)
      logic-not-delete-value: A # 逻辑未删除值(默认为 0)

logging:
  config: classpath:logback-spring.xml

ocr:
  language: chi_sim
  data-path: D:/OCR/chineseData
  APP_ID: 25305185
  API_KEY: uzmvGGytkX68K2L8YTw0LUa1
  SECRET_KEY: 4iuVt7oUxEdR2mH8UdqfqIP56Q47QRui

#  APP_ID: 25305037
#  API_KEY: ahdVNqlVg4h9raEuoOmLYS69
#  SECRET_KEY: 5ngu7kocqwXWbfFjH0xLh2v1q5XS4DEP

#  APP_ID: 25335117
#  API_KEY: hHl7rC5vQWIFWqkb2cMupny8
#  SECRET_KEY: 8Te4REPPIGmIO4w8ncY2GcnA4mBkBkKs

#  host: http://localhost:8080
  host: http://112.80.133.142:2000
  save-path: D:/union_management/download
#  save-path: /data/img


